export default {
  font: {
    family: {
      Poppins: 'Poppins',
      apple: '-apple-system',
      Segoe: 'Segoe UI',
      Roboto: 'Roboto',
      Oxygen: 'Oxygen',
      Ubuntu: 'Ubuntu',
      Cantarell: 'Cantarell',
      Sans: 'Open Sans',
      Helvetica: 'Helvetica Neue',
      default: 'sans-serif',
    },
    size: {
      nano: '0.625em',
      xnano: '0.75em',
      xxnano: '0.875em',
      small: '1em',
      xsmall: '1.125em',
      medium: '1.25em',
      large: '1.5em',
      xlarge: '2em',
      xxlarge: '2.5em',
      huge: '3em',
      big: '8.375em'
    },
  },
  colors: {
    primary: '#E2E2E2',
    secondary: '#FFFFFF',
    tertiary: '#bf4800',
    white: '#FFFFFF',
    whiteDark: '#B2B2B2',
    dark: '#000000',
    pink: '#EC008C',
    pinkLight: '#F173AC',
    cyan: '#00B098',
    grayLight: '#F5F5F7',
    gray: '#989899',
    grayDark: '#A7A7A7',
    dimGray: '#62626280',
    input: '#EBEBEB',
    grayMedium: '#444444',
    blue: '#217BD0',
    lightBlue: '#41B6E6',
    border: '#DEDEDE',
    success: '#2CB34A',
    greenTitle: '#338720',
    greenContainer: '#43B02A',
    error: '#EE3124',
    title: 'rgb(29, 29, 31)',
    veryDarkViolet: '#3C1053',
    successLight: '#94c93d',
    primaryLight: '#fbf9f6',
  },
  spacings: {
    nano: '0.25rem',
    xnano: '0.5rem',
    xxnano: '0.75rem',
    small: '1rem',
    xsmall: '1.25rem',
    medium: '1.5rem',
    large: '1.75rem',
    xlarge: '2rem',
    xxlarge: '2.25rem',
    huge: '2.5rem'
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
} as const;
